### ISSUE TITLE
Uncaught exception in sleeping thread

### ISSUE THREAD

**Issue by jwilson100** [darcy-framework/synq#25]
Thread [Thread-2] (Suspended (exception SleepInterruptedException))	
	ThreadedPollEvent<T>.waitUpTo(Duration) line: 117	
	SimpleTransitionEvent<T>(ForwardingPollEvent<T>).waitUpTo(Duration) line: 15	
	MultiEvent<T>.lambda$waitUpTo$18(Duration) line: 46	
	1834755909.run() line: not available	
	Thread.run() line: 745

**Comment by alechenninger** [comment]
Probably related to #12 

I'm probably doing something really bad somewhere. @dmcneil or @abocz wanna take a look?
